# .project metadata for Tekton
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "tekton"
name: "Tekton"
description: "A powerful and flexible open source framework for creating continuous integration and delivery (CI/CD) systems that allow developers to build, test, and deploy across multiple cloud providers and on-premises systems by abstracting away the underlying implementation details."
type: "project"
project_lead: tektoncd/governing-board
slack_channels:
  - name: "#general"
    workspace: "tekton"
    link: "https://join.slack.com/t/tektoncd/shared_invite/zt-1z8ctzsyv-wLXWwA2Rl3AOhcNGqpWRUw"
    primary: true

maturity_log:
  - phase: "incubating"
    date: "2026-07-10T16:20:26Z"
    issue: "https://github.com/cncf/toc/issues/2088"

repositories:
  - "https://github.com/tektoncd/pipeline"
  - "https://github.com/tektoncd/triggers"
  - "https://github.com/tektoncd/chains"
  - "https://github.com/tektoncd/results"
  - "https://github.com/tektoncd/cli"
  - "https://github.com/tektoncd/dashboard"
  - "https://github.com/tektoncd/operator"
  - "https://github.com/tektoncd/catalog"
  - "https://github.com/tektoncd/pipelines-as-code"
  - "https://github.com/tektoncd/pruner"
  - "https://github.com/tektoncd/community"
  - "https://github.com/tektoncd-catalog/git-clone"
  - "https://github.com/tektoncd-catalog/golang"
  - "https://github.com/tektoncd-catalog/kaniko"


website: "https://tekton.dev"

artwork: "https://raw.githubusercontent.com/cncf/artwork/main/projects/tekton/icon/color/tekton-icon-color.svg"

adopters:
  path: "https://github.com/tektoncd/community/blob/main/ADOPTERS.md"

package_managers:
  docker:
    - pipeline/*
    - triggers/*
    - chains/*
    - operator/*
    - results/*
    - pruner/*
    - pipelines-as-code/*
    - catalog/*
  homebrew: "tektoncd-cli"
  chocolatey: "tektoncd-cli"

social:
  twitter: "https://twitter.com/tektoncd"

security:
  policy:
    path: "https://github.com/tektoncd/.github/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/tektoncd/pipeline/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/tektoncd/pipeline/blob/main/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/tektoncd/.github/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: true
    cla_only: true
    cla_url:
      path: https://easycla.lfx.linuxfoundation.org/#/?version=2

documentation:
  readme:
    path: "https://tekton.dev/docs"

landscape:
  category: "App Definition and Development"
  subcategory: "Continuous Integration & Delivery"

# CLOMonitor Score: 91/100
# Documentation: 99 | License: 92 | Best Practices: 79 | Security: 72
